# Cf. http://docs.travis-ci.com/user/getting-started/
# Cf. http://docs.travis-ci.com/user/languages/go/

language: go
os: osx

# Ask for OS X 10.10, since we require fchmodat(2) to be available.
osx_image: xcode6.4

# We don't use `sudo`, so opt in to Travis's faster container-based infrastructure.
# Cf. http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

# We can't build with 1.4.1 (the default as of 2016-01-02), because it doesn't
# support vendoring.
go: 1.5.2

# Ensure that we get vendoring support in `go test`.
env:
  - GO15VENDOREXPERIMENT=1

# All of our dependencies are in the repo, so we don't need to run `go get`. In
# fact we actively don't want to do so, because this will help us diagnose
# accidentally unvendored dependencies.
#
# So use the `true` command to do nothing for the install step.
install: true
